spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    #      url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://00.00.00.00:3306/sys?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${{ secrets.MYSQL_PASSWORD}}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    general-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create